repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy CALM/
        language: system
        pass_filenames: false
        types: [python]
