from __future__ import annotations
from datetime import datetime
import argparse
import shlex
from pathlib import Path
from typing import Iterable



def default_replay_name(out_dir: str | None) -> str:
    ts = datetime.now().strftime("%Y_%m_%d_%H_%M")
    name = f"{ts}_calm_replay.log"
    if out_dir:
        return str(Path(out_dir) / name)
    return name

def none_or_int(x: str) -> Optional[int]:
    # Enables faithful round-trip for --Until None
    return None if x.lower() == "none" else int(x)


def load_replay_args(path: str) -> list[str]:
    argv: list[str] = []
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        argv.extend(shlex.split(s))
    return argv

def write_replay_file(path: str, parser: argparse.ArgumentParser, ns: argparse.Namespace) -> None:
    """
    Write a re-runnable "replay" file that encodes the *entire* effective configuration,
    including defaults.

    Notes:
    - Lines beginning with '#' are comments.
    - For boolean flags created with BooleanOptionalAction, we can write explicit
      --foo or --no-foo.
    - For store_true/store_false without a negative option, False cannot be expressed
      on the CLI; we write a commented line to document it.
    """
    out = []
    out.append("# Replay file generated by CALM")
    out.append("# Non-comment lines are parsed as CLI tokens (shlex.split).")
    out.append("")
    out.append(f"# Generated: {datetime.now().isoformat(timespec='seconds')}")
    out.append(f"# Working directory: {Path.cwd()}")
    out.append("")

    # Separate optionals and positionals to preserve typical CLI ordering
    optionals: list[argparse.Action] = []
    positionals: list[argparse.Action] = []

    for action in parser._actions:
        if action.dest in ("help", "replay", "out_replay"):
            continue
        if action.option_strings:
            optionals.append(action)
        else:
            # positional arguments
            if action.dest != argparse.SUPPRESS:
                positionals.append(action)

    # ----- Write optionals -----
    for action in optionals:
        dest = action.dest
        cur = getattr(ns, dest)

        # Prefer a long option if present
        opt = next((s for s in action.option_strings if s.startswith("--")), action.option_strings[-1])

        # BooleanOptionalAction (best: explicit True/False)
        if isinstance(action, argparse.BooleanOptionalAction):
            if cur is True:
                out.append(shlex.quote(opt))
            else:
                # argparse creates the negated option strings; pick the one starting with --no-
                neg = next((s for s in action.option_strings if s.startswith("--no-")), None)
                if neg:
                    out.append(shlex.quote(neg))
                else:
                    out.append(f"# {opt} set to False (no explicit --no- form found)")
            continue

        # store_true / store_false
        if isinstance(action, argparse._StoreTrueAction):
            if cur:
                out.append(shlex.quote(opt))
            else:
                # Can't encode False without an explicit negation flag
                out.append(f"# {opt} is False (cannot be expressed without a --no-* option)")
            continue

        if isinstance(action, argparse._StoreFalseAction):
            if cur is False:
                out.append(shlex.quote(opt))
            else:
                out.append(f"# {opt} is True (cannot be expressed without a --no-* option)")
            continue

        # Multi-value options
        if action.nargs in ("+", "*") or isinstance(cur, (list, tuple)):
            parts = [opt] + [str(x) for x in (cur or [])]
            out.append(" ".join(shlex.quote(p) for p in parts))
            continue

        # Single value options
        out.append(" ".join(shlex.quote(p) for p in (opt, str(cur))))

    # ----- Write positionals (in order) -----
    if positionals:
        out.append("")
        out.append("# Positional arguments")
        for action in positionals:
            cur = getattr(ns, action.dest, None)
            if cur is None:
                continue
            if isinstance(cur, (list, tuple)):
                for x in cur:
                    out.append(shlex.quote(str(x)))
            else:
                out.append(shlex.quote(str(cur)))

    Path(path).write_text("\n".join(out) + "\n", encoding="utf-8")


if __name__=="__main__":
    pass