import argparse
import os
import MDAnalysis as mda
import numpy as np
import glob
from typing import List, Optional, Sequence, Dict

_ROTATION_ANGLE_TOLERANCE = 1e-9  # radians; distinguishes "q_mn present but --rotate wasn't used" (theta == 0.0 exactly) from a real rotation


def build_rotation_tcl(sft, out_path: str) -> bool:
    """Generate a VMD TCL script that, once sourced against an already-loaded
    ORIGINAL trajectory (same -F/-S/-U stride as used to build `sft`, so
    frame i here lines up with frame i of the fit), rotates every atom
    per-frame to match the rotation alignment used by 'CALM analyze full
    --rotate', and sets up a representation that only *displays* residues
    within the region that stays meaningful across the whole trajectory (the
    same-centered circle, of fixed radius, that fits in every frame's box -
    see analyze/analyze.py's circle_cutter). Rotation is applied to the whole
    system, not just that subset - only the displayed selection is
    restricted.

    Returns True and writes out_path if q_mn shows a real rotation was used;
    returns False (writes nothing) if q_mn is present but --rotate wasn't
    actually used during the build (theta ~ 0 for every frame).
    """
    from ..core.rotation import recover_rotation_angle  # deferred: avoids a
    # circular import (core.fourier_build -> utilize -> get_vmd_visualization
    # -> core.fourier_sft/rotation)

    n_frames, _, M, N = sft.q_mn.shape
    Nx = (M - 1) // 2
    Ny = (N - 1) // 2

    thetas = np.empty(n_frames)
    for i in range(n_frames):
        Lx, Ly = sft.dimensions[i, 0], sft.dimensions[i, 1]
        thetas[i] = recover_rotation_angle(sft.q_mn[i], Lx, Ly, Nx, Ny)

    if not np.any(np.abs(thetas) > _ROTATION_ANGLE_TOLERANCE):
        return False

    cx = sft.dimensions[:, 0] / 2.0
    cy = sft.dimensions[:, 1] / 2.0
    # Fixed radius across the whole trajectory: circle_cutter's per-frame
    # radius is min(Lx,Ly)/2 of THAT frame's box, and all these circles share
    # the same center (Lx/2, Ly/2 of their own frame) - so the region valid
    # in every frame is simply the smallest of these radii. Rotation pivots
    # around (cx, cy) too, so distance-from-center - and thus this selection
    # - is unaffected by whether it's evaluated before or after rotating.
    radius = float(np.min(np.minimum(sft.dimensions[:, 0], sft.dimensions[:, 1])) / 2.0)
    thetas_deg = np.degrees(thetas)

    lines = [
        "# Auto-generated by CALM link write_xtc",
        "#",
        "# Rotates EVERY atom, per frame, to match the rotation alignment used by",
        "# 'CALM analyze full --rotate'. Separately sets up a representation that",
        "# only *displays* residues within the region that stays meaningful across",
        f"# every frame (fixed radius {radius:.6f} Angstrom around each frame's own",
        "# box center) - the rotation itself is NOT restricted to that subset.",
        "#",
        "# Usage: load your ORIGINAL trajectory in VMD first (same -F/-S/-U stride",
        "# used to build this fit, so frame i here lines up with frame i of the fit),",
        "# then 'source' this script. Edit $molid below if the original trajectory",
        "# isn't the top/most-recently-loaded molecule.",
        "",
        "set molid [molinfo top]",
        f"set radius {radius:.6f}",
        "set frame_cx { " + " ".join(f"{v:.6f}" for v in cx) + " }",
        "set frame_cy { " + " ".join(f"{v:.6f}" for v in cy) + " }",
        "set frame_theta_deg { " + " ".join(f"{v:.6f}" for v in thetas_deg) + " }",
        "",
        "set nf [molinfo $molid get numframes]",
        'if {$nf != [llength $frame_theta_deg]} {',
        '    puts "WARNING: molecule has $nf frames but this script has [llength $frame_theta_deg] - check your -F/-S/-U match the analyze run."',
        "}",
        "",
        "# Representation restricted to the shared circle. selupdate isn't enough",
        "# here since the circle's center (frame_cx/frame_cy) can drift under NPT -",
        "# selupdate only auto-tracks x/y/z against a FIXED selection string, so the",
        "# selection text itself is rebuilt with that frame's center every iteration.",
        "mol representation Lines",
        "mol color Name",
        "mol selection \"same residue as (sqr(x-[lindex $frame_cx 0])+sqr(y-[lindex $frame_cy 0]) <= sqr($radius))\"",
        "mol addrep $molid",
        "set repid [expr {[molinfo $molid get numreps] - 1}]",
        "",
        "for {set i 0} {$i < $nf} {incr i} {",
        "    animate goto $i",
        "    set cx [lindex $frame_cx $i]",
        "    set cy [lindex $frame_cy $i]",
        "    set deg [lindex $frame_theta_deg $i]",
        "",
        "    # Rotate EVERY atom (whole system), not just the displayed subset.",
        '    set all_sel [atomselect $molid "all" frame $i]',
        "    set pivot [list $cx $cy 0]",
        "    set neg_pivot [vecinvert $pivot]",
        "    set M [transmult [transoffset $pivot] [transaxis z $deg] [transoffset $neg_pivot]]",
        "    $all_sel move $M",
        "    $all_sel delete",
        "",
        "    # Representation: only DISPLAY residues within the shared circle.",
        '    mol modselect $repid $molid "same residue as (sqr(x-$cx)+sqr(y-$cy) <= sqr($radius))"',
        "}",
        "",
        'puts "Done: rotated all atoms for $nf frames; representation $repid shows residues within radius $radius of each frame\'s own box center."',
    ]

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    return True


def get_vmd_visualisation(curvature_dir: str, out_dir: str):
    """Build pseudo-universe from Z_fitted_*.npy files,
    write GRO (first frame), XTC trajectory, and average GRO.

    Grid points that are NaN (e.g. outside the inscribed circle after
    --rotate's circle_cutter masking, see analyze/analyze.py - only that
    region stays meaningful across differently-rotated frames) are dropped
    entirely rather than written as NaN coordinates, which MDAnalysis's GRO
    writer rejects outright. circle_cutter's radius is min(Lx,Ly)/2 using
    *that frame's* box size, which can drift in an NPT run - so which grid
    cells are NaN isn't necessarily identical across frames. A single
    trajectory needs a fixed atom count, so we use the intersection of every
    frame's valid points (conservative: NaN in even one frame drops that
    point everywhere), rather than assuming the first frame's mask applies
    to all of them.
    """

    # --- Load box size ---
    dim_file = os.path.join(curvature_dir, "dimensions.csv")
    box_size = np.loadtxt(dim_file, delimiter=",", skiprows=1,
                          max_rows=1, usecols=(1, 2, 3))

    # --- Find all Z_fitted files ---
    z_files = sorted(glob.glob(os.path.join(curvature_dir, "*_Z_fitted.npy")))
    if not z_files:
        raise FileNotFoundError(
            f"No *_Z_fitted*.npy files found in {curvature_dir}"
        )

    print(f"Found {len(z_files)} frames.")

    # --- Grid shape from the first frame ---
    n_layers, Nx, Ny = np.load(z_files[0]).shape

    x = np.linspace(0, box_size[0], Nx, endpoint=False)
    y = np.linspace(0, box_size[1], Ny, endpoint=False)
    X, Y = np.meshgrid(x, y)

    # --- Points valid (non-NaN) across every frame ---
    valid = np.ones((Nx, Ny), dtype=bool)
    for z_file in z_files:
        valid &= ~np.any(np.isnan(np.load(z_file)), axis=0)

    if not valid.any():
        raise ValueError(
            f"No grid points are valid (non-NaN) across all {len(z_files)} frames in {curvature_dir}"
        )
    X_valid, Y_valid = X[valid], Y[valid]
    n_valid = int(valid.sum())

    def build_coords(z_array):
        return np.vstack([
            np.column_stack([X_valid,
                             Y_valid,
                             z_array[l][valid]])
            for l in range(n_layers)
        ])

    z_values = np.load(z_files[0]) * 10
    coords = build_coords(z_values)

    resindices = np.repeat(np.arange(n_layers), n_valid)
    u = mda.Universe.empty(
        n_atoms=coords.shape[0],
        n_residues=n_layers,
        atom_resindex=resindices,
        trajectory=True
    )

    for attr in ["name", "resname", "resid"]:
        u.add_TopologyAttr(attr)

    u.atoms.names = ["C"] * coords.shape[0]
    u.residues.resnames = ["upper", "lower", "middle"][:n_layers]
    u.residues.resids = list(range(1, n_layers + 1))
    u.dimensions = [*box_size, 90.0, 90.0, 90.0]

    # Output paths
    gro_path = os.path.join(out_dir, "first_frame.gro")
    xtc_path = os.path.join(out_dir, "trajectory.xtc")
    avg_gro_path = os.path.join(out_dir, "average_structure.gro")

    # Write first frame GRO
    u.atoms.positions = coords
    u.atoms.write(gro_path)


    # --- Trajectory + averaging ---
    avg_z = np.zeros_like(z_values)

    with mda.coordinates.XTC.XTCWriter(
            xtc_path, n_atoms=u.atoms.n_atoms) as writer:

        for z_file in z_files:
            z_values = np.load(z_file) *10
            avg_z += z_values

            u.atoms.positions = build_coords(z_values)
            writer.write(u.atoms)


    # --- Average structure ---
    avg_z /= len(z_files)
    u.atoms.positions = build_coords(avg_z)
    u.atoms.write(avg_gro_path)


def write_xtc(args: List[str]) -> None:

    parser = argparse.ArgumentParser(description="Create GRO + XTC of fitting from CALM analyze output files",formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-i", "--input",help="Folder containing *_Z_fitted.npy and dimensions.csv")
    parser.add_argument("-o", "--output",help="Folder to store generated GRO and XTC files")
    args = parser.parse_args(args)

    os.makedirs(args.output, exist_ok=True)
    get_vmd_visualisation(args.input, args.output)

    # If this directory also has the raw SFT (Amn.npy/qmn.npy/dimensions.npy -
    # the common case when it came from 'CALM analyze full' without --sft),
    # and q_mn shows a real rotation was used, also emit a VMD TCL script.
    from ..core.fourier_sft import SFT  # deferred: avoids a circular import
    # (core.fourier_build -> utilize -> get_vmd_visualization -> core.fourier_sft)
    try:
        sft = SFT.from_directory(args.input)
    except FileNotFoundError:
        sft = None

    if sft is not None:
        tcl_path = os.path.join(args.output, "rotate_and_select.tcl")
        if build_rotation_tcl(sft, tcl_path):
            print(f"Rotation detected in q_mn: wrote VMD script to {tcl_path}")
        else:
            print("q_mn found but shows no rotation was applied (--rotate wasn't used) - skipping VMD script.")


if __name__ == "__main__":
    pass





