import argparse
import os
import MDAnalysis as mda
import numpy as np
import glob
from typing import List, Optional, Sequence, Dict

def build_rotation_tcl(sft, out_path: str) -> bool:
    """Generate a VMD TCL script that, once sourced against an already-loaded
    ORIGINAL trajectory (same -F/-S/-U stride as used to build `sft`, so
    frame i here lines up with frame i of the fit), rotates every atom
    per-frame to match the rotation alignment used by 'CALM analyze full
    --rotate', and sets up a representation that only *displays* residues
    within the region that stays meaningful across the whole trajectory (the
    same-centered circle, of fixed radius, that fits in every frame's box -
    see analyze/analyze.py's circle_cutter). Rotation is applied to the whole
    system, not just that subset - only the displayed selection is
    restricted.

    Returns True and writes out_path if q_mn shows a real rotation was used;
    returns False (writes nothing) if q_mn is present but --rotate wasn't
    actually used during the build (theta ~ 0 for every frame).
    """
    from ..core.rotation import recover_all_rotation_angles, rotation_was_used, fixed_circle_radius  # deferred: avoids a
    # circular import (core.fourier_build -> utilize -> get_vmd_visualization
    # -> core.fourier_sft/rotation)

    if not rotation_was_used(sft):
        return False

    thetas = recover_all_rotation_angles(sft)
    cx = sft.dimensions[:, 0] / 2.0
    cy = sft.dimensions[:, 1] / 2.0
    # Rotation pivots around (cx, cy) too, so distance-from-center - and thus
    # this selection - is unaffected by whether it's evaluated before or
    # after rotating.
    radius = fixed_circle_radius(sft)
    thetas_deg = np.degrees(thetas)

    lines = [
        "# Auto-generated by CALM link write_xtc",
        "#",
        "# Rotates EVERY atom, per frame, to match the rotation alignment used by",
        "# 'CALM analyze full --rotate'. Separately sets up a representation that",
        "# only *displays* residues within the region that stays meaningful across",
        f"# every frame (fixed radius {radius:.6f} Angstrom around each frame's own",
        "# box center) - the rotation itself is NOT restricted to that subset.",
        "#",
        "# Usage: load your ORIGINAL trajectory in VMD first (same -F/-S/-U stride",
        "# used to build this fit, so frame i here lines up with frame i of the fit),",
        "# then 'source' this script. Edit $molid below if the original trajectory",
        "# isn't the top/most-recently-loaded molecule.",
        "",
        "set molid [molinfo top]",
        f"set radius {radius:.6f}",
        "set frame_cx { " + " ".join(f"{v:.6f}" for v in cx) + " }",
        "set frame_cy { " + " ".join(f"{v:.6f}" for v in cy) + " }",
        "set frame_theta_deg { " + " ".join(f"{v:.6f}" for v in thetas_deg) + " }",
        "",
        "set nf [molinfo $molid get numframes]",
        'if {$nf != [llength $frame_theta_deg]} {',
        '    puts "WARNING: molecule has $nf frames but this script has [llength $frame_theta_deg] - check your -F/-S/-U match the analyze run."',
        "}",
        "",
        "# Representation restricted to the shared circle. selupdate isn't enough",
        "# here since the circle's center (frame_cx/frame_cy) can drift under NPT -",
        "# selupdate only auto-tracks x/y/z against a FIXED selection string, so the",
        "# selection text itself is rebuilt with that frame's center every iteration.",
        "mol representation Lines",
        "mol color Name",
        "mol selection \"same residue as (sqr(x-[lindex $frame_cx 0])+sqr(y-[lindex $frame_cy 0]) <= sqr($radius))\"",
        "mol addrep $molid",
        "set repid [expr {[molinfo $molid get numreps] - 1}]",
        "",
        "for {set i 0} {$i < $nf} {incr i} {",
        "    animate goto $i",
        "    set cx [lindex $frame_cx $i]",
        "    set cy [lindex $frame_cy $i]",
        "    set deg [lindex $frame_theta_deg $i]",
        "",
        "    # Rotate EVERY atom (whole system), not just the displayed subset.",
        '    set all_sel [atomselect $molid "all" frame $i]',
        "    set pivot [list $cx $cy 0]",
        "    set neg_pivot [vecinvert $pivot]",
        "    set M [transmult [transoffset $pivot] [transaxis z $deg] [transoffset $neg_pivot]]",
        "    $all_sel move $M",
        "    $all_sel delete",
        "",
        "    # Representation: only DISPLAY residues within the shared circle.",
        '    mol modselect $repid $molid "same residue as (sqr(x-$cx)+sqr(y-$cy) <= sqr($radius))"',
        "}",
        "",
        'puts "Done: rotated all atoms for $nf frames; representation $repid shows residues within radius $radius of each frame\'s own box center."',
    ]

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    return True


def _frame_number(path):
    return int(os.path.basename(path).split("_")[0])


def _trajectory_hole_union(sft, z_files, grid_shape):
    """Per-layer (upper, lower) boolean mask, True where that grid point was
    unsupported by the fit (--Remove-TMD) in ANY frame being visualized.

    GRO+XTC atom names are set once for the whole topology, not per frame -
    unlike Z_fitted's NaN-per-point (which can vary frame to frame), a single
    trajectory can't rename an atom differently in different frames. So a
    hole that only shows up in some frames (e.g. a moving TMD) still needs
    marking for the whole trajectory: the union, not any single frame's mask.

    Rotation-aware (per-frame lookup via lookup_mask_at_rotated_grid) if
    --rotate was used, matching map/plot.py's approach - same reasoning:
    hole_mask was computed on the unrotated, as-fit grid at build time, so it
    has to be remapped onto each frame's rotated output grid before use.
    """
    from ..core.rotation import (
        rotation_was_used, recover_all_rotation_angles, lookup_mask_at_rotated_grid,
    )

    rotate = rotation_was_used(sft)
    thetas = recover_all_rotation_angles(sft) if rotate else None

    upper_union = np.zeros(grid_shape, dtype=bool)
    lower_union = np.zeros(grid_shape, dtype=bool)

    for z_file in z_files:
        matches = np.nonzero(sft.frame_indices == _frame_number(z_file))[0]
        if not matches.size:
            continue
        idx = matches[0]
        upper, lower = sft.hole_mask[idx]

        if rotate:
            Lx, Ly = sft.dimensions[idx, 0], sft.dimensions[idx, 1]
            gridsize = upper.shape[0]
            x = np.linspace(0, Lx, gridsize, endpoint=False)
            y = np.linspace(0, Ly, gridsize, endpoint=False)
            X, Y = np.meshgrid(x, y)
            cx, cy = Lx / 2.0, Ly / 2.0
            upper = lookup_mask_at_rotated_grid(upper, X, Y, Lx, Ly, cx, cy, thetas[idx])
            lower = lookup_mask_at_rotated_grid(lower, X, Y, Lx, Ly, cx, cy, thetas[idx])

        upper_union |= upper
        lower_union |= lower

    return upper_union, lower_union


def get_vmd_visualisation(curvature_dir: str, out_dir: str, sft=None):
    """Build pseudo-universe from Z_fitted_*.npy files,
    write GRO (first frame), XTC trajectory, and average GRO.

    Grid points that are NaN (e.g. outside the inscribed circle after
    --rotate's circle_cutter masking, see analyze/analyze.py - only that
    region stays meaningful across differently-rotated frames) are dropped
    entirely rather than written as NaN coordinates, which MDAnalysis's GRO
    writer rejects outright. circle_cutter's radius is min(Lx,Ly)/2 using
    *that frame's* box size, which can drift in an NPT run - so which grid
    cells are NaN isn't necessarily identical across frames. A single
    trajectory needs a fixed atom count, so we use the intersection of every
    frame's valid points (conservative: NaN in even one frame drops that
    point everywhere), rather than assuming the first frame's mask applies
    to all of them.

    If `sft` is given and has a hole_mask (--Remove-TMD was used to build),
    grid points with no real fitting support (in any frame, unioned - see
    _trajectory_hole_union) are kept and given atom name "S" instead of "C",
    so a user can filter them out in VMD via "not name S" without changing
    the atom count. This is deliberately a different mechanism from the
    circle exclusion above: circle-excluded points are dropped outright, hole
    points are only renamed. Z_fitted's values are never altered for holes
    either way - only the atom name changes.
    """

    # --- Load box size ---
    dim_file = os.path.join(curvature_dir, "dimensions.csv")
    box_size = np.loadtxt(dim_file, delimiter=",", skiprows=1,
                          max_rows=1, usecols=(1, 2, 3))

    # --- Find all Z_fitted files ---
    z_files = sorted(glob.glob(os.path.join(curvature_dir, "*_Z_fitted.npy")))
    if not z_files:
        raise FileNotFoundError(
            f"No *_Z_fitted*.npy files found in {curvature_dir}"
        )

    print(f"Found {len(z_files)} frames.")

    # --- Grid shape from the first frame ---
    n_layers, Nx, Ny = np.load(z_files[0]).shape

    x = np.linspace(0, box_size[0], Nx, endpoint=False)
    y = np.linspace(0, box_size[1], Ny, endpoint=False)
    X, Y = np.meshgrid(x, y)

    # --- Points valid (non-NaN) across every frame ---
    valid = np.ones((Nx, Ny), dtype=bool)
    for z_file in z_files:
        valid &= ~np.any(np.isnan(np.load(z_file)), axis=0)

    if not valid.any():
        raise ValueError(
            f"No grid points are valid (non-NaN) across all {len(z_files)} frames in {curvature_dir}"
        )
    X_valid, Y_valid = X[valid], Y[valid]
    n_valid = int(valid.sum())

    def build_coords(z_array):
        return np.vstack([
            np.column_stack([X_valid,
                             Y_valid,
                             z_array[l][valid]])
            for l in range(n_layers)
        ])

    z_values = np.load(z_files[0]) * 10
    coords = build_coords(z_values)

    resindices = np.repeat(np.arange(n_layers), n_valid)
    u = mda.Universe.empty(
        n_atoms=coords.shape[0],
        n_residues=n_layers,
        atom_resindex=resindices,
        trajectory=True
    )

    for attr in ["name", "resname", "resid"]:
        u.add_TopologyAttr(attr)

    if sft is not None and sft.hole_mask is not None:
        upper_union, lower_union = _trajectory_hole_union(sft, z_files, (Nx, Ny))
        hole_by_layer = [upper_union, lower_union, upper_union | lower_union][:n_layers]
        name_blocks = []
        for l in range(n_layers):
            block = np.full(n_valid, "C", dtype="<U1")
            block[hole_by_layer[l][valid]] = "S"
            name_blocks.append(block)
        u.atoms.names = np.concatenate(name_blocks).tolist()
    else:
        u.atoms.names = ["C"] * coords.shape[0]
    u.residues.resnames = ["upper", "lower", "middle"][:n_layers]
    u.residues.resids = list(range(1, n_layers + 1))
    u.dimensions = [*box_size, 90.0, 90.0, 90.0]

    # Output paths
    gro_path = os.path.join(out_dir, "first_frame.gro")
    xtc_path = os.path.join(out_dir, "trajectory.xtc")
    avg_gro_path = os.path.join(out_dir, "average_structure.gro")

    # Write first frame GRO
    u.atoms.positions = coords
    u.atoms.write(gro_path)


    # --- Trajectory + averaging ---
    avg_z = np.zeros_like(z_values)

    with mda.coordinates.XTC.XTCWriter(
            xtc_path, n_atoms=u.atoms.n_atoms) as writer:

        for z_file in z_files:
            z_values = np.load(z_file) *10
            avg_z += z_values

            u.atoms.positions = build_coords(z_values)
            writer.write(u.atoms)


    # --- Average structure ---
    avg_z /= len(z_files)
    u.atoms.positions = build_coords(avg_z)
    u.atoms.write(avg_gro_path)


def write_xtc(args: List[str]) -> None:

    parser = argparse.ArgumentParser(description="Create GRO + XTC of fitting from CALM analyze output files",formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-i", "--input",help="Folder containing *_Z_fitted.npy and dimensions.csv")
    parser.add_argument("-o", "--output",help="Folder to store generated GRO and XTC files")
    args = parser.parse_args(args)

    os.makedirs(args.output, exist_ok=True)

    # Load once, reused both for hole-mask atom naming (get_vmd_visualisation)
    # and, below, for the rotation TCL script - the common case when this
    # directory came from 'CALM analyze full' without --sft.
    from ..core.fourier_sft import SFT  # deferred: avoids a circular import
    # (core.fourier_build -> utilize -> get_vmd_visualization -> core.fourier_sft)
    try:
        sft = SFT.from_directory(args.input)
    except FileNotFoundError:
        sft = None

    get_vmd_visualisation(args.input, args.output, sft=sft)

    if sft is not None:
        tcl_path = os.path.join(args.output, "rotate_and_select.tcl")
        if build_rotation_tcl(sft, tcl_path):
            print(f"Rotation detected in q_mn: wrote VMD script to {tcl_path}")
        else:
            print("q_mn found but shows no rotation was applied (--rotate wasn't used) - skipping VMD script.")


if __name__ == "__main__":
    pass





