from __future__ import annotations

import argparse
import glob
import os

import MDAnalysis as mda
import numpy as np

from ..core.fourier_build import _close_enclosed_gaps
from ..core.fourier_sft import SFT
from ..core.manual import add_manual
from ..core.rotation import (
    fixed_circle_radius,
    lookup_mask_at_rotated_grid,
    recover_all_rotation_angles,
    rotation_was_used,
)
from ..map.plot import _frame_number


def build_rotation_tcl(sft: SFT, out_path: str) -> bool:
    """Write a VMD TCL script that rotates every atom per frame to match 'CALM analyze full --rotate'.

    Sourced against the ORIGINAL trajectory (same -F/-S/-U stride used to
    build `sft`, so frame i lines up with frame i of the fit). Also sets up
    a representation that only displays residues within the fixed-radius
    circle shared by every frame (see `analyze/analyze.py`'s
    `circle_cutter`); rotation itself applies to the whole system, not just
    that displayed subset.

    Returns True and writes `out_path` if q_mn shows a real rotation was
    used; returns False (writes nothing) if q_mn is present but --rotate
    wasn't actually used during the build.
    """
    if not rotation_was_used(sft):
        return False

    thetas = recover_all_rotation_angles(sft)
    assert sft.dimensions is not None
    cx = sft.dimensions[:, 0] / 2.0
    cy = sft.dimensions[:, 1] / 2.0
    radius = fixed_circle_radius(sft.dimensions)
    thetas_deg = np.degrees(thetas)

    lines = [
        "# Auto-generated by CALM link write_xtc",
        "#",
        "# Rotates EVERY atom, per frame, to match the rotation alignment used by",
        "# 'CALM analyze full --rotate'. Separately sets up a representation that",
        "# only *displays* residues within the region that stays meaningful across",
        f"# every frame (fixed radius {radius:.6f} Angstrom around each frame's own",
        "# box center) - the rotation itself is NOT restricted to that subset.",
        "#",
        "# Usage: load your ORIGINAL trajectory in VMD first (same -F/-S/-U stride",
        "# used to build this fit, so frame i here lines up with frame i of the fit),",
        "# then 'source' this script. Edit $molid below if the original trajectory",
        "# isn't the top/most-recently-loaded molecule.",
        "",
        "set molid [molinfo top]",
        f"set radius {radius:.6f}",
        "set frame_cx { " + " ".join(f"{v:.6f}" for v in cx) + " }",
        "set frame_cy { " + " ".join(f"{v:.6f}" for v in cy) + " }",
        "set frame_theta_deg { " + " ".join(f"{v:.6f}" for v in thetas_deg) + " }",
        "",
        "set nf [molinfo $molid get numframes]",
        'if {$nf != [llength $frame_theta_deg]} {',
        '    puts "WARNING: molecule has $nf frames but this script has '
        '[llength $frame_theta_deg] - check your -F/-S/-U match the analyze run."',
        "}",
        "",
        "# Representation restricted to the shared circle. selupdate isn't enough",
        "# here since the circle's center (frame_cx/frame_cy) can drift under NPT -",
        "# selupdate only auto-tracks x/y/z against a FIXED selection string, so the",
        "# selection text itself is rebuilt with that frame's center every iteration.",
        "mol representation Lines",
        "mol color Name",
        "mol selection \"same residue as (sqr(x-[lindex $frame_cx 0])+sqr(y-[lindex $frame_cy 0]) <= sqr($radius))\"",
        "mol addrep $molid",
        "set repid [expr {[molinfo $molid get numreps] - 1}]",
        "",
        "for {set i 0} {$i < $nf} {incr i} {",
        "    animate goto $i",
        "    set cx [lindex $frame_cx $i]",
        "    set cy [lindex $frame_cy $i]",
        "    set deg [lindex $frame_theta_deg $i]",
        "",
        "    # Rotate EVERY atom (whole system), not just the displayed subset.",
        '    set all_sel [atomselect $molid "all" frame $i]',
        "    set pivot [list $cx $cy 0]",
        "    set neg_pivot [vecinvert $pivot]",
        "    set M [transmult [transoffset $pivot] [transaxis z $deg] [transoffset $neg_pivot]]",
        "    $all_sel move $M",
        "    $all_sel delete",
        "",
        "    # Representation: only DISPLAY residues within the shared circle.",
        '    mol modselect $repid $molid "same residue as (sqr(x-$cx)+sqr(y-$cy) <= sqr($radius))"',
        "}",
        "",
        'puts "Done: rotated all atoms for $nf frames; representation $repid shows '
        'residues within radius $radius of each frame\'s own box center."',
    ]

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    return True


def _trajectory_hole_union(
    sft: SFT, z_files: list[str], grid_shape: tuple
) -> tuple:
    """Per-layer (upper, lower) mask, True where a grid point was unsupported
    by the fit (--Remove-TMD) in ANY visualized frame.

    Atom names are set once for the whole topology, not per frame, so this
    unions every visualized frame's hole mask into one mask that marks the
    whole trajectory: a point flagged in even a single frame (e.g. a
    moving TMD passing over it) stays marked for the whole video.

    Rotation-aware (per-frame lookup via `lookup_mask_at_rotated_grid`) if
    --rotate was used: `hole_mask` was computed on the unrotated, as-fit
    grid at build time, and is remapped onto each frame's rotated output
    grid before use.

    Each frame's own mask was already closed (`_close_enclosed_gaps`) at
    build time, but combining different frames' masks with OR - and, under
    --rotate, remapping each onto the output grid - can each carve out new
    small enclosed gaps that no single frame's own closing pass ever saw.
    Applying `_close_enclosed_gaps` again here, to the combined result,
    closes those too.
    """
    rotate = rotation_was_used(sft)
    thetas = recover_all_rotation_angles(sft) if rotate else None

    upper_union = np.zeros(grid_shape, dtype=bool)
    lower_union = np.zeros(grid_shape, dtype=bool)

    assert sft.frame_indices is not None
    assert sft.hole_mask is not None
    for z_file in z_files:
        matches = np.nonzero(sft.frame_indices == _frame_number(z_file))[0]
        if not matches.size:
            continue
        idx = matches[0]
        upper, lower = sft.hole_mask[idx]

        if rotate:
            assert sft.dimensions is not None
            assert thetas is not None
            Lx, Ly = sft.dimensions[idx, 0], sft.dimensions[idx, 1]
            gridsize = upper.shape[0]
            x = np.linspace(0, Lx, gridsize, endpoint=False)
            y = np.linspace(0, Ly, gridsize, endpoint=False)
            X, Y = np.meshgrid(x, y)
            cx, cy = Lx / 2.0, Ly / 2.0
            upper = lookup_mask_at_rotated_grid(upper, X, Y, Lx, Ly, cx, cy, thetas[idx])
            lower = lookup_mask_at_rotated_grid(lower, X, Y, Lx, Ly, cx, cy, thetas[idx])

        upper_union |= upper
        lower_union |= lower

    return _close_enclosed_gaps(upper_union), _close_enclosed_gaps(lower_union)


def _build_coords(
    z_array: np.ndarray, X_valid: np.ndarray, Y_valid: np.ndarray, valid: np.ndarray, n_layers: int
) -> np.ndarray:
    """Stack (x, y, z) coordinates for every valid grid point, one block per layer."""
    return np.vstack([
        np.column_stack([X_valid, Y_valid, z_array[layer][valid]])
        for layer in range(n_layers)
    ])


def get_vmd_visualisation(curvature_dir: str, out_dir: str, sft: SFT) -> None:
    """Build a pseudo-universe from *_Z_fitted.npy files; write GRO (first frame), XTC trajectory, and average GRO.

    Grid points that are NaN in any frame (e.g. outside the inscribed
    circle after --rotate's `circle_cutter` masking) are dropped from the
    atom count entirely, so MDAnalysis's GRO writer always receives real
    coordinates. A trajectory's fixed atom count uses the intersection of
    every frame's valid points, since which points are NaN can differ per
    frame (box size can drift under NPT).

    If `sft` has a hole_mask (--Remove-TMD was used to build), grid points
    with no real fitting support in any frame (see
    `_trajectory_hole_union`) are kept but renamed from atom name "C" to
    "S", so they can be filtered out in VMD with "not name S" without
    changing the atom count. Z_fitted's values are copied unchanged either
    way; only the atom name differs.
    """
    assert sft.dimensions is not None
    box_size = sft.dimensions[0]

    z_files = sorted(glob.glob(os.path.join(curvature_dir, "*_Z_fitted.npy")))
    if not z_files:
        raise FileNotFoundError(
            f"No *_Z_fitted*.npy files found in {curvature_dir}"
        )

    print(f"Found {len(z_files)} frames.")

    n_layers, Nx, Ny = np.load(z_files[0]).shape

    x = np.linspace(0, box_size[0], Nx, endpoint=False)
    y = np.linspace(0, box_size[1], Ny, endpoint=False)
    X, Y = np.meshgrid(x, y)

    valid = np.ones((Nx, Ny), dtype=bool)
    for z_file in z_files:
        valid &= ~np.any(np.isnan(np.load(z_file)), axis=0)

    if not valid.any():
        raise ValueError(
            f"No grid points are valid (non-NaN) across all {len(z_files)} frames in {curvature_dir}"
        )
    X_valid, Y_valid = X[valid], Y[valid]
    n_valid = int(valid.sum())

    z_values = np.load(z_files[0]) * 10
    coords = _build_coords(z_values, X_valid, Y_valid, valid, n_layers)

    resindices = np.repeat(np.arange(n_layers), n_valid)
    u = mda.Universe.empty(
        n_atoms=coords.shape[0],
        n_residues=n_layers,
        atom_resindex=resindices,
        trajectory=True
    )

    for attr in ["name", "resname", "resid"]:
        u.add_TopologyAttr(attr)

    if sft is not None and sft.hole_mask is not None:
        upper_union, lower_union = _trajectory_hole_union(sft, z_files, (Nx, Ny))
        hole_by_layer = [upper_union, lower_union, upper_union | lower_union][:n_layers]
        name_blocks = []
        for layer in range(n_layers):
            block = np.full(n_valid, "C", dtype="<U1")
            block[hole_by_layer[layer][valid]] = "S"
            name_blocks.append(block)
        u.atoms.names = np.concatenate(name_blocks).tolist()
    else:
        u.atoms.names = ["C"] * coords.shape[0]
    u.residues.resnames = ["upper", "lower", "middle"][:n_layers]
    u.residues.resids = list(range(1, n_layers + 1))
    u.dimensions = [*box_size, 90.0, 90.0, 90.0]

    gro_path = os.path.join(out_dir, "first_frame.gro")
    xtc_path = os.path.join(out_dir, "trajectory.xtc")
    avg_gro_path = os.path.join(out_dir, "average_structure.gro")

    u.atoms.positions = coords
    u.atoms.write(gro_path)

    avg_z = np.zeros_like(z_values)

    with mda.coordinates.XTC.XTCWriter(
            xtc_path, n_atoms=u.atoms.n_atoms) as writer:

        for z_file in z_files:
            z_values = np.load(z_file) * 10
            avg_z += z_values

            u.atoms.positions = _build_coords(z_values, X_valid, Y_valid, valid, n_layers)
            writer.write(u.atoms)

    avg_z /= len(z_files)
    u.atoms.positions = _build_coords(avg_z, X_valid, Y_valid, valid, n_layers)
    u.atoms.write(avg_gro_path)


def vmd_xtc(args: list[str]) -> None:
    """CLI entry: export a 'CALM analyze full' run's fitted surface as GRO + XTC for VMD."""
    parser = argparse.ArgumentParser(description="Export the fitted surface as a GRO + XTC trajectory for VMD")
    parser.add_argument("-i", "--input", help="directory with *_Z_fitted.npy and Amn.npy/qmn.npy/dimensions.npy")
    parser.add_argument("-o", "--output", help="output directory")
    add_manual(parser, "link_vmd_xtc")
    ns = parser.parse_args(args)

    os.makedirs(ns.output, exist_ok=True)

    sft = SFT.from_directory(ns.input)
    get_vmd_visualisation(ns.input, ns.output, sft=sft)

    tcl_path = os.path.join(ns.output, "rotate_and_select.tcl")
    if build_rotation_tcl(sft, tcl_path):
        print(f"Rotation detected in q_mn: wrote VMD script to {tcl_path}")
    else:
        print("q_mn found but shows no rotation was applied (--rotate wasn't used) - skipping VMD script.")


if __name__ == "__main__":
    pass
